version: '2.2'

services:

#
# @version  1.0.0
# @author   https://github.com/linusniederer
# @link     https://github.com/linusniederer/docker-templates/templates/php
# @date     13.02.2023
#
  php:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: php
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./app:/app