version: '2.2'

services:

#
# @version  1.0.0
# @author   https://github.com/linusniederer
# @link     https://github.com/linusniederer/docker-templates/templates/nginx
# @date     13.02.2023
#
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ=Europe/Berlin 
    ports:
      - 8080:8080
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    restart: always